const { describe, expect, test } = require('@jest/globals');
const { spawnSync } = require('node:child_process');
const { pickRandomMessage } = require('./main.js');

describe('functional tests', () => {
    test('command line application runs when called', () => {
        // Mark sits down, and wants to explore the various random messages that
        // could be generated by this new random message generator he just installed.
        // He opens up his favorite terminal/command line/shell, and types in the
        // command: node main.js
        let child = spawnSync('node', ['main.js']);

        output = child.stdout.toString()

        expect(output).toBeTruthy();
        // His node.js application runs, producing some random output. Satisfied,
        // he returns to whatever it was that he was doing previously.
    })
})

describe('unit tests', () => {
    test('test pickRandomMessage', () => {
        exampleMessageArray = [
            'message one',
            'message two',
            'message three',
        ]

        let message_picked = pickRandomMessage(exampleMessageArray);

        expect(exampleMessageArray).toContain(message_picked);
    });
})
