const { describe, expect, test } = require('@jest/globals');
const { execSync } = require('node:child_process')

describe('functional tests', () => {
    test('command line application runs when called', () => {
        // Mark sits down, and wants to explore the various random messages that
        // could be generated by this new random message generator he just installed.
        // He opens up his favorite terminal/command line/shell, and types in the
        // command: npm run
        let output;

        execSync('npm run main', (error, stdout, stderr) => {
            if (error) {
                console.error(`exec error: ${error}`);
            }
            output = stdout;
        });

        expect(output).toBeTruthy();
        // His node.js application runs, producing some random output. Satisfied,
        // he returns to whatever it was that he was doing previously.

    })
})
